version: '3.9'

services:
  mysql:
    image: mysql:8.0
    network_mode: bridge
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./database/:/var/lib/mysql/

  backend:
    build: backend
    network_mode: bridge
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql